image: "cgenius/crossbuild:win"


build:
  stage: build
  script:
    - echo hello

cp_pkg:
  stage: deploy
  script:
    - mkdir -p /tmp/output
    - cp *.zip /tmp/output
  artifacts:
    paths:
      - output/*.zip
    expire_in: 1 week
