image: "cgenius/crossbuild:win"

prepare:
  stage: .pre
  script:
    - echo "hello world"

build:
  stage: build
  script:
    - make package

cp_pkg:
  stage: deploy
  script:
    - mkdir -p /tmp/output
    - cp *.zip /tmp/output
  artifacts:
    paths:
      - output/*.zip
    expire_in: 1 week
