image: cgenius/crossbuild:win

windows:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - mkdir -p /tmp && cd "$_"
    - mkdir -p $CI_PROJECT_DIR/output
    - cmake -DCMAKE_TOOLCHAIN_FILE="$OLDPWD/toolchains/toolchain-mingw.cmake" -DCMAKE_BUILD_TYPE=Release -DUSE_BOOST=0 -DUSE_LUA=1 -DPULL_DLLS=1 -DAPPEND_SHA=1 -DSDL2_MIXER_INCLUDE_DIR=/usr/x86_64-w64-mingw32/include/SDL2 -DSDL2_INCLUDE_DIR=/usr/x86_64-w64-mingw32/include/SDL2 "$OLDPWD"
  script:
    - make package
    - cp *.zip $CI_PROJECT_DIR/output
  artifacts:
    name: "CGenius-Win-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 week
    paths:
      - output/*
