stages:
    - build
    - publish

windowsportable:
    image: cgenius/crossbuild:win
    stage: build    
    # instead of calling g++ directly you can also use some build toolkit like make
    # install the necessary build tools when needed
    before_script:
      - mkdir -p /tmp && cd "$_"
      - mkdir -p $CI_PROJECT_DIR/output
      - cmake -DCMAKE_TOOLCHAIN_FILE="$OLDPWD/toolchains/toolchain-mingw.cmake" -DCMAKE_BUILD_TYPE=Release -DUSE_BOOST=0 -DPULL_DLLS=1 -DAPPEND_SHA=1 -DSDL2_MIXER_INCLUDE_DIR=/usr/x86_64-w64-mingw32/include/SDL2 -DSDL2_INCLUDE_DIR=/usr/x86_64-w64-mingw32/include/SDL2 "$OLDPWD"
    script:
      - cmake --build .    
      - cpack -G ZIP
      - cp *.zip $CI_PROJECT_DIR/output
    artifacts:
      name: "CGenius-Win-$CI_COMMIT_SHORT_SHA"
      expire_in: 1 week
      paths:
        - output/*
        
windowsinstaller:
    image: cgenius/crossbuild:winnsis
    stage: build
    # instead of calling g++ directly you can also use some build toolkit like make
    # install the necessary build tools when needed
    before_script:
      - mkdir -p /tmp && cd "$_"
      - mkdir -p $CI_PROJECT_DIR/output
      - cmake -DCMAKE_TOOLCHAIN_FILE="$OLDPWD/toolchains/toolchain-mingw.cmake" -DCMAKE_BUILD_TYPE=Release -DUSE_BOOST=0 -DPULL_DLLS=1 -DAPPEND_SHA=1 -DSDL2_MIXER_INCLUDE_DIR=/usr/x86_64-w64-mingw32/include/SDL2 -DSDL2_INCLUDE_DIR=/usr/x86_64-w64-mingw32/include/SDL2 "$OLDPWD"
    script:
      - cmake --build .    
      - cpack -G NSIS
      - cp *.exe $CI_PROJECT_DIR/output
    artifacts:
      name: "CGenius-Win-$CI_COMMIT_SHORT_SHA"
      expire_in: 1 week
      paths:
        - output/*
                            
publish:
    image: inetprocess/gitlab-release
    stage: publish
    only:
        - tags
    dependencies: 
        - windowsportable
        - windowsinstaller
    script:
        - gitlab-release --message 'Automatic release files' ./output/*
              
