name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: create build-dir
      run: mkdir CGenius-Build
    - name: cd build-dir
      run: cd CGenius-Build
    - name: CMake     
      run: cmake ./ -DUSE_BOOST=0
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
